name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.11'

      - name: Setup Poetry
        run: |
          sudo apt install curl
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: Run Black
        run: |
          poetry run black ./src
          
      - name: Run Pylint
        run: |
          poetry run pylint --recursive=y .
